import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const app = await readFile(new URL('./App.jsx', import.meta.url), 'utf8')
const styles = await readFile(new URL('./styles/app-shell.css', import.meta.url), 'utf8')

test('global shell exposes the required settings and repository affordances', () => {
  assert.match(app, /SettingsPanel/)
  assert.match(app, /aria-label="Open Daymark on GitHub"/)
  assert.match(app, /https:\/\/github\.com\/Michaelunkai\/daymark-desktop/)
  assert.match(app, /onImport={importBackup}/)
  assert.match(app, /onReset={resetWorkspace}/)
  assert.match(app, /route === 'notes' \|\| route === 'diary'/)
  assert.match(app, /onTaskToggle={toggleTask}/)
  assert.match(app, /createLongPressReorderController/)
  assert.match(app, /onPointerDown=/)
  assert.match(app, /reorder-mode-help/)
  assert.match(app, /Nothing was changed\./)
  assert.match(app, /window\.DaymarkAI/)
  assert.match(app, /AGENT_BRIDGE_VERSION = 3/)
  assert.match(app, /BroadcastChannel\('daymark-agent'\)/)
  assert.match(app, /daymark:agent-request/)
  assert.match(app, /operation === 'createTask'/)
  assert.match(app, /operation === 'startSession'/)
  assert.match(app, /listSessions/)
  assert.match(app, /getViewState/)
  assert.match(app, /'section\.remove'/)
  assert.match(app, /data-agent-bridge="connected"/)
  assert.match(app, /AI access needs key/)
  assert.doesNotMatch(app, />Agent connected</)
  assert.match(app, /sectionComposerOpen/)
  assert.match(app, /data-section-reorder-id/)
  assert.match(app, /data-section-drop-id/)
  assert.match(app, /targetSectionId/)
  assert.match(app, /project\?\.description\?\.trim\(\)/)
  assert.match(app, /type: 'section\.add'/)
  assert.match(app, /sectionId: section\.id \?\? null/)
  assert.match(app, /function ConfirmationDialog/)
  assert.match(app, /const requestConfirmation =/)
  assert.match(app, /Delete from Order/)
  assert.match(app, /Related items will lose only this relationship\./)
  assert.match(app, /Revoke Daymark AI key\?/)
  assert.match(app, /Replace current workspace\?/)
  assert.match(app, /Reset local workspace\?/)
  assert.doesNotMatch(app, /window\.confirm/)
  assert.doesNotMatch(app, /maxLength\s*=/)
})

test('shell styles include keyboard focus, mobile layout, and dark theme coverage', () => {
  assert.match(styles, /button:focus-visible/)
  assert.match(styles, /\[data-theme="dark"\]/)
  assert.match(styles, /@media \(max-width: 720px\)/)
  assert.match(styles, /\.settings-grid/)
  assert.match(styles, /\.visually-hidden/)
  assert.match(styles, /\.journal-view/)
  assert.match(styles, /\.task-order-button/)
  assert.match(styles, /\.section-composer/)
  assert.match(styles, /\.section-order-button/)
  assert.match(styles, /\.is-reordering/)
  assert.match(styles, /\.agent-connection/)
  assert.match(styles, /\.app-shell\.sidebar-is-collapsed \.topbar/)
  assert.match(styles, /\.app-shell\.sidebar-is-collapsed \.topbar__brand > :not\(\.topbar__menu\)/)
  assert.match(styles, /\.main-content \{\s*grid-column: 1 \/ -1;/)
  assert.match(styles, /grid-template-columns: minmax\(0, 1fr\) repeat\(4, 34px\)/)
  assert.match(styles, /\.topbar__controls \.agent-connection \{[\s\S]*?font-size: 0;/)
  assert.match(styles, /\.topbar__controls \.topbar__divider \{[\s\S]*?display: none;/)
})
